site_name: Modelur User Guide
site_url: https://modelur.github.io/docs
theme: 'material'
nav:
- 1. Meet Modelur: index.md
- 2. Getting Started: getting-started.md
- 3. Quick Start: quickstart.md
- 4. Reference:
  - 'Menu': 'reference/menu.md'
  - 'Whole Plot': 'reference/whole_plot.md'
  - 'City Block': 'reference/city_block.md'
  - 'Land Use': 'reference/land_use.md'
  - 'Building': 'reference/building.md'
  - 'Survey': 'reference/survey.md'
  - 'Toolbar': 'reference/toolbar.md'
  - 'Extensions Menu': 'reference/extensions_menu.md'
  - 'GIS Import (Beta)': 'reference/gis.md'
- 5. Troubleshooting: troubleshooting.md
- 6. Appendix: appendix.md
extra_css:
- css/fonts.css
- css/custom.css
extra_javascript:
- javascript/mkdocs.js
copyright: Copyright (c) 2020 by <a href="http://agilicity.com" target="_blank">AgiliCity d.o.o.</a>. All Rights Reserved.
site_author: The Modelur Team
google_analytics: ['UA-184154467-1', 'auto']
extra:
  palette:
      primary: 'light blue'
      accent: 'cyan'
  font:
      text: 'Open Sans'
      code: 'Ubuntu Mono'
  author:
      twitter: 'modelur'
  social:
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/modelur'
    - icon: 'fontawesome/brands/linkedin'
      link: 'https://www.linkedin.com/company/agilicity'
markdown_extensions:
  - admonition
  - toc:
      permalink: True
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.keys