site_name: Modelur User Guide
pages:
- 1. Meet Modelur: index.md
- 2. Getting Started: getting-started.md
- 3. Quick Start: quickstart.md
- 4. Reference: reference.md
- 5. Troubleshooting: troubleshooting.md
- 6. Appendix: appendix.md
theme: 'material'
extra_css:
- css/fonts.css
- css/custom.css
copyright: Copyright 2016 by URBS. All Rights Reserved.
site_favicon: modelur.ico
site_author: The Modelur Team
google_analytics: ['UA-8035020-12', 'auto']
extra:
  palette:
      primary: 'light blue'
      accent: 'cyan'
  font:
      text: 'Open Sans'
      code: 'Ubuntu Mono'
  author:
      twitter: 'modelur'
markdown_extensions:
  - admonition